algorithm: edac
env: walker2d-medium-v2
seed: 0
eval_freq: 5000
n_episodes: 10
max_timesteps: 1000000
w2_weights:
- 10.0
- 10.0
num_actors: 3
sinkhorn_K: 4
sinkhorn_blur: 0.05
sinkhorn_backend: tensorized
num_critics: 10
eta: 1.0
alpha_learning_rate: 3e-4
actor_lr: 3e-4
batch_size: 256
discount: 0.99
tau: 0.005
buffer_size: 2000000
normalize: true
normalize_reward: false
use_wandb: true
project: PORL
group: pogo-multi-edac-walker2d
name: pogo-multi-edac-walker2d-medium-v2
