1# POGO Multi-Actor with TD3_BC algorithm
# TD3_BC의 구조(Critic, Actor)를 그대로 사용하되, Actor만 multi-actor

algorithm: td3_bc  # 필수: 사용할 알고리즘 선택

env: halfcheetah-medium-v2
seed: 0
eval_freq: 5000
n_episodes: 10
max_timesteps: 1000000

# POGO Multi-Actor
w2_weights: [10.0, 10.0, 10.0]
num_actors: 3

# Sinkhorn
sinkhorn_K: 4
sinkhorn_blur: 0.05
sinkhorn_backend: "tensorized"

# TD3_BC 파라미터 (TD3_BC 구조 그대로 사용)
alpha: 2.5
policy_noise: 0.2
noise_clip: 0.5
policy_freq: 2
qf_lr: 3e-4
actor_lr: 3e-4

# 공통
batch_size: 256
discount: 0.99
tau: 0.005
buffer_size: 2000000
normalize: true
normalize_reward: false

project: CORL
group: pogo-multi-td3-bc
name: pogo-multi-td3-bc
