dataset_name: antmaze-umaze-v2
train_seed: 0
eval_seed: 42
w2_weights:
# Algorithm
algorithm: fql
- 10.0
- 10.0
num_actors: 3
actor_configs:
- type: deterministic
- type: deterministic
- type: deterministic
sinkhorn_K: 4
sinkhorn_blur: 0.05
sinkhorn_backend: auto
actor_learning_rate: 0.0003
critic_learning_rate: 0.0003
hidden_dim: 512
actor_n_hiddens: 4
critic_n_hiddens: 4
gamma: 0.999
tau: 0.005
actor_bc_coef: 0.003
critic_bc_coef: 0.002
actor_ln: false
critic_ln: true
policy_noise: 0.2
noise_clip: 0.5
policy_freq: 2
normalize_q: true
q_agg: mean
normalize_q_loss: false
alpha: 10.0
flow_steps: 10
batch_size: 256
num_epochs: 1000
num_updates_on_epoch: 1000
normalize_reward: true
normalize_states: false
eval_episodes: 100
eval_freq: 50000
project: PORL
group: pogo-multi-fql
name: pogo-multi-fql-antmaze_umaze_v2
